POST http://localhost:5000/api/phones HTTP/1.1
Content-Type: application/json

{
  "model": "SE",
  "brand": "Apple",
  "year": 2020,
  "memoryStorageCapacity": 64,
  "processor": "Apple Ax",
  "screenSize": 4.7,
  "NFC": true
}

###

GET http://localhost:5000/api/phones HTTP/1.1

###

GET http://localhost:5000/api/phones/:phoneId HTTP/1.1


###